module.exports = { 'View slds-list--vertical slds-has-dividers--bottom-space slds-has-list-interactions':
   { marginTop: 0,
     marginBottom: 0,
     marginLeft: 0,
     marginRight: 0,
     paddingTop: 0,
     paddingBottom: 0,
     paddingLeft: 0,
     paddingRight: 0 },
  'Text slds-list--vertical slds-has-dividers--bottom-space slds-has-list-interactions': {},
  'View slds-list__item slds-not-selected':
   { paddingTop: 12,
     paddingBottom: 12,
     paddingLeft: 12,
     paddingRight: 12,
     borderBottomWidth: 1,
     borderBottomColor: '#d8dde6' },
  'Text slds-list__item slds-not-selected': {},
  'View slds-media slds-tile': { alignItems: 'flex-start' },
  'Text slds-media slds-tile': {},
  'View slds-media__figure': { marginRight: 12 },
  'Text slds-media__figure': {},
  'View slds-icon icon-doctype-zip': { width: 32, height: 32, borderRadius: 4, overflow: 'hidden' },
  'Text slds-icon icon-doctype-zip': {},
  'View use': {},
  'Text use': {},
  'View slds-media__body': { marginBottom: 0, flex: 1 },
  'Text slds-media__body': {},
  'View slds-tile__title slds-truncate':
   { marginTop: 0,
     marginBottom: 0,
     marginLeft: 0,
     marginRight: 0,
     paddingTop: 0,
     paddingBottom: 0,
     paddingLeft: 0,
     paddingRight: 0,
     position: 'relative',
     overflow: 'hidden' },
  'Text slds-tile__title slds-truncate': {},
  'View a': { backgroundColor: 'transparent' },
  'Text a': { color: '#0070d2' },
  'View slds-tile__detail slds-list--horizontal slds-has-dividers slds-text-body--small':
   { marginTop: 0,
     marginBottom: 0,
     marginLeft: 0,
     marginRight: 0,
     paddingTop: 0,
     paddingBottom: 0,
     paddingLeft: 0,
     paddingRight: 0,
     position: 'relative' },
  'Text slds-tile__detail slds-list--horizontal slds-has-dividers slds-text-body--small': { fontSize: 12, color: '#54698d' },
  'View slds-truncate slds-list__item':
   { marginRight: 0,
     paddingRight: 0,
     position: 'relative',
     alignSelf: 'center',
     overflow: 'hidden' },
  'Text slds-truncate slds-list__item': {} };