module.exports = {
  'View slds-tile': {},
  'Text slds-tile': {},
  'View slds-tile__title slds-truncate':
   { marginTop: 0,
     marginBottom: 0,
     marginLeft: 0,
     marginRight: 0,
     paddingTop: 0,
     paddingBottom: 0,
     paddingLeft: 0,
     paddingRight: 0,
     position: 'relative',
     overflow: 'hidden' },
  'Text slds-tile__title slds-truncate': {},
  'View a': { backgroundColor: 'transparent' },
  'Text a': { color: '#0070d2' },
  'View slds-tile__detail slds-text-body--small': { position: 'relative' },
  'Text slds-tile__detail slds-text-body--small': { fontSize: 12, color: '#54698d' },
  'View slds-truncate':
   { marginTop: 0,
     marginBottom: 0,
     marginLeft: 0,
     marginRight: 0,
     paddingTop: 0,
     paddingBottom: 0,
     paddingLeft: 0,
     paddingRight: 0,
     overflow: 'hidden' },
  'Text slds-truncate': {} };