module.exports = { 'View slds-page-header':
   { paddingTop: 16,
     paddingBottom: 16,
     paddingLeft: 12,
     paddingRight: 12,
     borderBottomWidth: 1,
     backgroundColor: '#f4f6f9',
     borderBottomColor: '#d8dde6' },
  'Text slds-page-header': {},
  'View slds-media': { alignItems: 'flex-start' },
  'Text slds-media': {},
  'View slds-media__figure': { marginRight: 12 },
  'Text slds-media__figure': {},
  'View slds-icon slds-icon--large slds-icon-standard-opportunity':
   { width: 48,
     height: 48,
     backgroundColor: '#fcb95b',
     borderRadius: 4,
     overflow: 'hidden' },
  'Text slds-icon slds-icon--large slds-icon-standard-opportunity': {},
  'View use': {},
  'Text use': {},
  'View slds-media__body': { marginBottom: 0, flex: 1 },
  'Text slds-media__body': {},
  'View slds-page-header__title slds-truncate slds-align-middle':
   { marginTop: 2,
     marginBottom: 0,
     marginLeft: 0,
     marginRight: 0,
     paddingTop: 0,
     paddingBottom: 0,
     paddingLeft: 0,
     paddingRight: 0,
     alignSelf: 'center',
     overflow: 'hidden' },
  'Text slds-page-header__title slds-truncate slds-align-middle': { fontSize: 18, fontWeight: '300' },
  'View slds-text-body--small slds-page-header__info':
   { marginTop: 4,
     marginBottom: 0,
     marginLeft: 0,
     marginRight: 0,
     paddingTop: 0,
     paddingBottom: 0,
     paddingLeft: 0,
     paddingRight: 0 },
  'Text slds-text-body--small slds-page-header__info': { fontSize: 12, color: '#54698d' } };