module.exports = {
  'View slds-list__item': 
   { paddingTop: 0,
     paddingBottom: 0,
     paddingLeft: 0,
     paddingRight: 0,
     borderBottomWidth: 1,
     borderBottomColor: '#d8dde6' },
  'Text slds-list__item': {},
  'View a': 
   { paddingTop: 12,
     paddingBottom: 12,
     paddingLeft: 12,
     paddingRight: 12,
     backgroundColor: 'transparent' },
  'Text a': { color: '#0070d2' },
  'View slds-truncate': 
   { marginTop: 0,
     marginBottom: 0,
     marginLeft: 0,
     marginRight: 0,
     paddingTop: 0,
     paddingBottom: 0,
     paddingLeft: 0,
     paddingRight: 0,
     overflow: 'hidden' },
  'Text slds-truncate': {},
  'View slds-icon_container slds-icon_container--circle slds-icon-action-share-post slds-m-right--medium': 
   { marginRight: 16,
     paddingTop: 8,
     paddingBottom: 8,
     paddingLeft: 8,
     paddingRight: 8,
     backgroundColor: '#65cae4',
     borderRadius: 0 },
  'Text slds-icon_container slds-icon_container--circle slds-icon-action-share-post slds-m-right--medium': {},
  'View slds-icon slds-icon--small': { width: 24, height: 24, borderRadius: 4, overflow: 'hidden' },
  'Text slds-icon slds-icon--small': {},
  'View use': {},
  'Text use': {},
  'View span': {},
  'Text span': {},
};